# GitLab CI pour Ruleset-as-Code

stages:
  - lint
  - verify
  - package
  - deploy

default:
  image: python:3.12-slim
  before_script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends libxml2-utils ca-certificates openssh-client git
    - python --version
  cache:
    paths:
      - .cache/pip

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"

xml:lint:
  stage: lint
  script:
    - bash .gitlab/ci/scripts/lint_xml.sh
  artifacts:
    when: always
    reports: {}

python:check_ids:
  stage: verify
  script:
    - bash .gitlab/ci/scripts/check_rule_ids.sh
  needs: ["xml:lint"]
  artifacts:
    when: always
    reports: {}

deploy:wazuh:
  stage: deploy
  script:
    - bash .gitlab/ci/scripts/integrate_rulesets.sh
  needs:
    - xml:lint
    - python:check_ids
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
      allow_failure: false
    - if: '$CI_COMMIT_TAG'
      when: on_success
      allow_failure: false
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
      allow_failure: true
  environment:
    name: wazuh
    action: start
